baseURL = "https://yogcat.github.io"
languageCode = "zh-CN"
title = "普通小站惹"
theme = "LeaveIt"

hasCJKLanguage = true

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "读书"
    url = "/books/"
    weight = 1

  [[menu.main]]
    name = "瞎写"
    url = "/nonsense/"
    weight = 2

  # [[menu.main]]
  #  name = "日志"
  #  url = "/posts/"
  #  weight = 2

  #[[menu.main]]
  #  name = "分类"
  #  url = "/categories/"
  #  weight = 3

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4

[params]
    since = 2020
    author = "努力逆熵的阿撒托斯"                           # Author's name
    avatar = "/images/me/yuki1.jpg"           # Author's avatar
    subtitle = "嗯学"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""

    toc = true                # 是否开启目录
    autoCollapseToc = true   # Auto expand and collapse toc
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

# [params.social]
   # GitHub = "xxoo"
   # Twitter = "xxoo"
   # Email   = "xxoo"
   # Instagram = "xxoo"
   # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
   # Facebook = "xxoo"
   # Telegram = "xxoo"
   # Dribbble = "xxoo"
   # Medium = "xxoo"
